### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by sjlagasse** [clickspider/Tea-Cozy#1]
**Criteria 1: HTML Structure  (4/4)**

Your HTML looks good. Nice job using a variety of different HTML elements to render your page. Nice use of comments and good indentation
 
**Criteria 2: Visual Layout (4/4)**

You did a great job on your final product. It looks just like the solution page which is great! All of the elements are there and they are in the right place.

 
**Criteria 3: Use of Flexbox (4/4)**

Great job using flex. All of your elements line up perfectly.
 
**Criteria 4: Implementation of Design Specification and Content (4/4)**

As said before, everything looks great!

**Overall Score: 16/16**

You did a great job on your webpage. Everything was in the right place. I like that you styled your page exactly to the mock. Great job getting you nav items to work in your nav. Great use of comments in your HTML. Lastly, good job using flex correctly. All in all, awesome job!

**Comment by clickspider** [comment]
thank you!!
